=== enaud1984/PAT/util/json_fake/schema/PIC/PICDettaglioCarriSchema.json
{
    "$id": "https://it.almaviva/drivebelt/pic/dettagliocarri.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "PIC Dettaglio Carri",
    "type": "object",
    "properties": {
        "IDTreno": {
            "type": "string",
            "description": "Codice alfanumerico che identifica il treno"
        },
        "IDTratta": {
            "type": "string",
            "description": "Codice alfanumerico che identifica la tratta"
        },
		"Progressivo": {
                "type": "number",
                "description": "Progressivo localit√†"
		},
        "DataOraPrevistoArrivo": {
            "type": "string",
            "format": "date-time",
            "description": "Data e ora prevista arrivo del treno"
        },
        "DataOraPrevistoPartenza": {
            "type": "string",
            "format": "date-time",
            "description": "Data e ora prevista partenza del treno"
        },
        "Origine": {
            "type": "string",
            "description": "Stazione di origine"
        },
        "Destinazione": {
            "type": "string",
            "description": "Stazione di destinazione"
        },
        "IDCarro": {
            "type": "string",
            "description": "Codice alfanumerico che identifica il carro"
        },
        "KmPercorsi": {
            "type": "number",
            "description": "Km percorsi"
        },
        "CarroRetrofillato": {
            "type": "string",
            "description": "Flag carro retrofillato"
        }
    },
	"required": ["IDTreno"]
}

=== enaud1984/PAT/scripts/drivebelt/PIC_DettaglioCarri/pic_dettaglio_carri_2.json
[{
		"IDTreno": "axajh82323",
		"IDTratta": "dkj734lk",
		"Progressivo": 34,
		"DataOraPrevistoArrivo": "2022-02-01T00:00:00",
		"DataOraPrevistoPartenza": "2022-02-01T00:00:00",
		"Origine": "Pescara",
		"Destinazione": "Ancona",
		"IDCarro": "asdh283",
		"KmPercorsi": 300,
		"CarroRetrofillato": "retrofilato"
}]
